using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ReelsCommerceSystem.Domain.Entities.ProductEntites;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReelsCommerceSystem.Infrastructure.Persistence.DataSeeding
{
    public class ProductSeeding : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> builder)
        {
            builder.HasData([
                // -------------------- Brand 1: NovaWear – Sustainable fashion --------------------
                new Product { Id = 1, Name = "EcoFlex T-Shirt", Description = "Breathable organic cotton tee for everyday comfort.", Category = "Clothing", Price = 29.99m, Quantity = 120, MediaUrl = "https://example.com/media/novawear_tshirt.jpg", IsCustomizable = false, DiscountPercentage = 10, BrandId = 1, CreatedAt = new DateTime(2022, 4, 12) },
                new Product { Id = 2, Name = "ReVibe Denim Jacket", Description = "Stylish recycled denim jacket for a sustainable look.", Category = "Clothing", Price = 79.99m, Quantity = 80, MediaUrl = "https://example.com/media/novawear_jacket.jpg", IsCustomizable = true, DiscountPercentage = 20, BrandId = 1, CreatedAt = new DateTime(2024, 2, 5) },
                new Product { Id = 3, Name = "EcoStride Sneakers", Description = "Lightweight sneakers made from recycled fibers.", Category = "Footwear", Price = 89.99m, Quantity = 150, MediaUrl = "https://example.com/media/novawear_sneakers.jpg", IsCustomizable = false, DiscountPercentage = 30, BrandId = 1, CreatedAt = new DateTime(2021, 8, 19) },
                new Product { Id = 4, Name = "Bamboo Breeze Hoodie", Description = "Soft hoodie crafted from sustainable bamboo fabric.", Category = "Clothing", Price = 59.99m, Quantity = 100, MediaUrl = "https://example.com/media/novawear_hoodie.jpg", IsCustomizable = true, DiscountPercentage = 40, BrandId = 1, CreatedAt = new DateTime(2023, 5, 7) },
                new Product { Id = 5, Name = "ReLeaf Tote Bag", Description = "Eco-friendly tote bag with minimalist design.", Category = "Accessories", Price = 19.99m, Quantity = 200, MediaUrl = "https://example.com/media/novawear_tote.jpg", IsCustomizable = false, BrandId = 1, CreatedAt = new DateTime(2020, 9, 28) },
                new Product { Id = 6, Name = "NatureFlow Pants", Description = "Comfortable pants made from recycled polyester.", Category = "Clothing", Price = 54.99m, Quantity = 90, MediaUrl = "https://example.com/media/novawear_pants.jpg", IsCustomizable = false, BrandId = 1, CreatedAt = new DateTime(2025, 3, 14) },
                
                // -------------------- Brand 2: TechEase – Smart accessories --------------------
                new Product { Id = 7, Name = "SyncCharge Cable", Description = "Fast-charging braided USB-C cable with smart chip.", Category = "Electronics", Price = 14.99m, Quantity = 300, MediaUrl = "https://example.com/media/techease_cable.jpg", DiscountPercentage = 10, BrandId = 2, CreatedAt = new DateTime(2024, 8, 22) },
                new Product { Id = 8, Name = "SmartDock Pro", Description = "Multi-device charging dock with wireless pad.", Category = "Electronics", Price = 49.99m, Quantity = 120, MediaUrl = "https://example.com/media/techease_dock.jpg", DiscountPercentage = 20, BrandId = 2, CreatedAt = new DateTime(2021, 12, 3) },
                new Product { Id = 9, Name = "AirPulse Earbuds", Description = "Noise-cancelling Bluetooth earbuds with 24h battery.", Category = "Audio", Price = 89.99m, Quantity = 200, MediaUrl = "https://example.com/media/techease_earbuds.jpg", DiscountPercentage = 30, BrandId = 2, CreatedAt = new DateTime(2022, 6, 9) },
                new Product { Id = 10, Name = "MagGrip Phone Mount", Description = "Smart magnetic car mount with auto-lock system.", Category = "Accessories", Price = 24.99m, Quantity = 150, MediaUrl = "https://example.com/media/techease_mount.jpg", DiscountPercentage = 40, BrandId = 2, CreatedAt = new DateTime(2023, 11, 18) },
                new Product { Id = 11, Name = "PulseTrack Watch", Description = "Fitness smartwatch with heart-rate and sleep tracking.", Category = "Wearables", Price = 129.99m, Quantity = 80, MediaUrl = "https://example.com/media/techease_watch.jpg", BrandId = 2, CreatedAt = new DateTime(2020, 5, 13) },
                new Product { Id = 12, Name = "GlideCase", Description = "MagSafe-compatible slim phone case.", Category = "Accessories", Price = 19.99m, Quantity = 180, MediaUrl = "https://example.com/media/techease_case.jpg", BrandId = 2, CreatedAt = new DateTime(2025, 1, 4) },
                
                // -------------------- Brand 3: Glowify – Natural skincare --------------------
                new Product { Id = 13, Name = "HydraBloom Serum", Description = "Vitamin C serum that brightens and smooths skin.", Category = "Skincare", Price = 39.99m, Quantity = 120, MediaUrl = "https://example.com/media/glowify_serum.jpg", DiscountPercentage = 10, BrandId = 3, CreatedAt = new DateTime(2023, 2, 25) },
                new Product { Id = 14, Name = "PureDew Cleanser", Description = "Gentle cleanser with aloe and green tea.", Category = "Skincare", Price = 19.99m, Quantity = 200, MediaUrl = "https://example.com/media/glowify_cleanser.jpg", DiscountPercentage = 20, BrandId = 3, CreatedAt = new DateTime(2021, 7, 14) },
                new Product { Id = 15, Name = "LumiMist Toner", Description = "Hydrating toner that refines pores naturally.", Category = "Skincare", Price = 24.99m, Quantity = 150, MediaUrl = "https://example.com/media/glowify_toner.jpg", DiscountPercentage = 30, BrandId = 3, CreatedAt = new DateTime(2022, 10, 9) },
                new Product { Id = 16, Name = "Radiant Night Cream", Description = "Rich moisturizer for overnight skin repair.", Category = "Skincare", Price = 44.99m, Quantity = 100, MediaUrl = "https://example.com/media/glowify_nightcream.jpg", DiscountPercentage = 40, BrandId = 3, CreatedAt = new DateTime(2024, 3, 27) },
                new Product { Id = 17, Name = "GlowShield Sunscreen", Description = "SPF 50 mineral sunscreen with lightweight feel.", Category = "Skincare", Price = 29.99m, Quantity = 180, MediaUrl = "https://example.com/media/glowify_sunscreen.jpg", BrandId = 3, CreatedAt = new DateTime(2020, 9, 10) },
                new Product { Id = 18, Name = "SilkTouch Moisturizer", Description = "All-day hydration for sensitive skin.", Category = "Skincare", Price = 34.99m, Quantity = 160, MediaUrl = "https://example.com/media/glowify_moisturizer.jpg", BrandId = 3, CreatedAt = new DateTime(2025, 4, 2) },
                
                // -------------------- Brand 4: UrbanFuel – Premium streetwear --------------------
                new Product { Id = 19, Name = "StreetCore Hoodie", Description = "Oversized hoodie with minimalist street-style logo.", Category = "Clothing", Price = 64.99m, Quantity = 120, MediaUrl = "https://example.com/media/urbanfuel_hoodie.jpg", DiscountPercentage = 10, BrandId = 4, CreatedAt = new DateTime(2022, 12, 16) },
                new Product { Id = 20, Name = "UrbanFlex Joggers", Description = "Slim-fit joggers for comfort and performance.", Category = "Clothing", Price = 49.99m, Quantity = 100, MediaUrl = "https://example.com/media/urbanfuel_joggers.jpg", DiscountPercentage = 20, BrandId = 4, CreatedAt = new DateTime(2024, 8, 7) },
                new Product { Id = 21, Name = "FuelRunner Sneakers", Description = "Modern street sneakers with breathable mesh upper.", Category = "Footwear", Price = 89.99m, Quantity = 150, MediaUrl = "https://example.com/media/urbanfuel_sneakers.jpg", DiscountPercentage = 30, BrandId = 4, CreatedAt = new DateTime(2021, 3, 2) },
                new Product { Id = 22, Name = "CityWave Jacket", Description = "Lightweight windbreaker with waterproof coating.", Category = "Outerwear", Price = 99.99m, Quantity = 80, MediaUrl = "https://example.com/media/urbanfuel_jacket.jpg", DiscountPercentage = 40, BrandId = 4, CreatedAt = new DateTime(2023, 10, 20) },
                new Product { Id = 23, Name = "SnapEdge Cap", Description = "Classic snapback cap with embroidered logo.", Category = "Accessories", Price = 24.99m, Quantity = 200, MediaUrl = "https://example.com/media/urbanfuel_cap.jpg", BrandId = 4, CreatedAt = new DateTime(2020, 5, 29) },
                new Product { Id = 24, Name = "MetroLayer Tee", Description = "Soft cotton tee with subtle reflective branding.", Category = "Clothing", Price = 34.99m, Quantity = 140, MediaUrl = "https://example.com/media/urbanfuel_tee.jpg", BrandId = 4, CreatedAt = new DateTime(2025, 2, 11) },
                
                // -------------------- Brand 5: Zenora – Wellness lifestyle --------------------
                new Product { Id = 25, Name = "ZenMat Pro", Description = "Premium non-slip yoga mat made with eco rubber.", Category = "Fitness", Price = 59.99m, Quantity = 110, MediaUrl = "https://example.com/media/zenora_mat.jpg", DiscountPercentage = 10, BrandId = 5, CreatedAt = new DateTime(2022, 6, 19) },
                new Product { Id = 26, Name = "AromaBliss Diffuser", Description = "Ultrasonic diffuser with ambient lighting.", Category = "Wellness", Price = 39.99m, Quantity = 150, MediaUrl = "https://example.com/media/zenora_diffuser.jpg", DiscountPercentage = 20, BrandId = 5, CreatedAt = new DateTime(2020, 11, 12) },
                new Product { Id = 27, Name = "CalmWave Candle", Description = "Soy candle infused with lavender and chamomile.", Category = "Home", Price = 19.99m, Quantity = 180, MediaUrl = "https://example.com/media/zenora_candle.jpg", DiscountPercentage = 30, BrandId = 5, CreatedAt = new DateTime(2023, 9, 15) },
                new Product { Id = 28, Name = "Balance Bottle", Description = "Glass water bottle with bamboo lid and sleeve.", Category = "Wellness", Price = 24.99m, Quantity = 160, MediaUrl = "https://example.com/media/zenora_bottle.jpg", DiscountPercentage = 40, BrandId = 5, CreatedAt = new DateTime(2024, 1, 6) },
                new Product { Id = 29, Name = "Focus Journal", Description = "Guided journal for mindfulness and productivity.", Category = "Stationery", Price = 14.99m, Quantity = 200, MediaUrl = "https://example.com/media/zenora_journal.jpg", BrandId = 5, CreatedAt = new DateTime(2025, 3, 25) },
                new Product { Id = 30, Name = "Serenity Pillow Spray", Description = "Natural lavender mist for better sleep.", Category = "Wellness", Price = 17.99m, Quantity = 180, MediaUrl = "https://example.com/media/zenora_spray.jpg", BrandId = 5, CreatedAt = new DateTime(2021, 4, 17) },
                
                // -------------------- Brand 6: AeroFit – Smart fitness gear --------------------
                new Product { Id = 31, Name = "AeroTrack Smart Band", Description = "Fitness tracker with pulse and oxygen monitoring.", Category = "Wearables", Price = 79.99m, Quantity = 130, MediaUrl = "https://example.com/media/aerofit_band.jpg", DiscountPercentage = 10, BrandId = 6, CreatedAt = new DateTime(2020, 10, 3) },
                new Product { Id = 32, Name = "FlexCore Dumbbells", Description = "Adjustable dumbbells for home strength training.", Category = "Equipment", Price = 129.99m, Quantity = 90, MediaUrl = "https://example.com/media/aerofit_dumbbells.jpg", DiscountPercentage = 20, BrandId = 6, CreatedAt = new DateTime(2025, 1, 20) },
                new Product { Id = 33, Name = "PulsePro Chest Strap", Description = "Heart-rate strap compatible with popular apps.", Category = "Accessories", Price = 59.99m, Quantity = 100, MediaUrl = "https://example.com/media/aerofit_strap.jpg", DiscountPercentage = 30, BrandId = 6, CreatedAt = new DateTime(2023, 2, 8) },
                new Product { Id = 34, Name = "AeroMat Trainer", Description = "High-density mat ideal for HIIT and yoga.", Category = "Fitness", Price = 39.99m, Quantity = 140, MediaUrl = "https://example.com/media/aerofit_mat.jpg", DiscountPercentage = 40, BrandId = 6, CreatedAt = new DateTime(2022, 11, 22) },
                new Product { Id = 35, Name = "HydraFuel Bottle", Description = "Smart bottle that tracks hydration levels.", Category = "Accessories", Price = 34.99m, Quantity = 160, MediaUrl = "https://example.com/media/aerofit_bottle.jpg", BrandId = 6, CreatedAt = new DateTime(2024, 6, 11) },
                new Product { Id = 36, Name = "TrainLite Shorts", Description = "Lightweight shorts with moisture-wicking tech.", Category = "Apparel", Price = 29.99m, Quantity = 200, MediaUrl = "https://example.com/media/aerofit_shorts.jpg", BrandId = 6, CreatedAt = new DateTime(2021, 9, 1) },

                // -------------------- Brand 7: EcoNest – Eco-friendly home solutions --------------------
                new Product { Id = 37, Name = "EcoGlow Lamp", Description = "Bamboo desk lamp with rechargeable LED bulb.", Category = "Home Decor", Price = 49.99m, Quantity = 110, MediaUrl = "https://example.com/media/econest_lamp.jpg", DiscountPercentage = 10, BrandId = 7, CreatedAt = new DateTime(2022, 5, 12) },
                new Product { Id = 38, Name = "GreenWave Blanket", Description = "Soft throw blanket made from recycled cotton.", Category = "Home", Price = 59.99m, Quantity = 100, MediaUrl = "https://example.com/media/econest_blanket.jpg", DiscountPercentage = 20, BrandId = 7, CreatedAt = new DateTime(2023, 8, 9) },
                new Product { Id = 39, Name = "PlantPure Planter Set", Description = "Biodegradable planters perfect for indoor herbs.", Category = "Gardening", Price = 29.99m, Quantity = 180, MediaUrl = "https://example.com/media/econest_planters.jpg", DiscountPercentage = 30, BrandId = 7, CreatedAt = new DateTime(2021, 10, 14) },
                new Product { Id = 40, Name = "EcoFresh Diffuser", Description = "Natural reed diffuser with citrus essential oils.", Category = "Home Fragrance", Price = 24.99m, Quantity = 150, MediaUrl = "https://example.com/media/econest_diffuser.jpg", DiscountPercentage = 40, BrandId = 7, CreatedAt = new DateTime(2024, 2, 27) },
                new Product { Id = 41, Name = "PureBreeze Air Filter", Description = "Reusable air filter system for cleaner home air.", Category = "Appliances", Price = 99.99m, Quantity = 90, MediaUrl = "https://example.com/media/econest_filter.jpg", BrandId = 7, CreatedAt = new DateTime(2020, 6, 22) },
                new Product { Id = 42, Name = "Harmony Coasters", Description = "Cork coasters made from renewable materials.", Category = "Home Accessories", Price = 14.99m, Quantity = 200, MediaUrl = "https://example.com/media/econest_coasters.jpg", BrandId = 7, CreatedAt = new DateTime(2025, 1, 19) },
                
                // -------------------- Brand 8: ByteWave – Tech-driven accessories --------------------
                new Product { Id = 43, Name = "VoltSync Charger", Description = "High-speed GaN charger with dual USB-C output.", Category = "Electronics", Price = 39.99m, Quantity = 150, MediaUrl = "https://example.com/media/bytewave_charger.jpg", DiscountPercentage = 10, BrandId = 8, CreatedAt = new DateTime(2021, 9, 23) },
                new Product { Id = 44, Name = "StreamPad Mouse", Description = "Ergonomic wireless mouse with silent clicks.", Category = "Accessories", Price = 29.99m, Quantity = 180, MediaUrl = "https://example.com/media/bytewave_mouse.jpg", DiscountPercentage = 20, BrandId = 8, CreatedAt = new DateTime(2023, 11, 5) },
                new Product { Id = 45, Name = "DataShell SSD Case", Description = "Shockproof case for portable SSDs.", Category = "Storage", Price = 19.99m, Quantity = 220, MediaUrl = "https://example.com/media/bytewave_ssdcase.jpg", DiscountPercentage = 30, BrandId = 8, CreatedAt = new DateTime(2022, 4, 17) },
                new Product { Id = 46, Name = "WavePods Mini", Description = "Compact true wireless earbuds with clear audio.", Category = "Audio", Price = 59.99m, Quantity = 140, MediaUrl = "https://example.com/media/bytewave_earbuds.jpg", DiscountPercentage = 40, BrandId = 8, CreatedAt = new DateTime(2024, 9, 30) },
                new Product { Id = 47, Name = "NeonLink Cable Set", Description = "Color-coded USB-C and Lightning cable pack.", Category = "Accessories", Price = 24.99m, Quantity = 200, MediaUrl = "https://example.com/media/bytewave_cables.jpg", BrandId = 8, CreatedAt = new DateTime(2020, 3, 14) },
                new Product { Id = 48, Name = "GlideStand Laptop Dock", Description = "Foldable aluminum laptop stand with cooling vents.", Category = "Office", Price = 44.99m, Quantity = 130, MediaUrl = "https://example.com/media/bytewave_stand.jpg", BrandId = 8, CreatedAt = new DateTime(2025, 7, 26) },
                
                // -------------------- Brand 9: PureGlow – Clean & ethical skincare --------------------
                new Product { Id = 49, Name = "AquaRenew Cleanser", Description = "Refreshing foaming cleanser for daily use.", Category = "Skincare", Price = 24.99m, Quantity = 160, MediaUrl = "https://example.com/media/pureglow_cleanser.jpg", DiscountPercentage = 10, BrandId = 9, CreatedAt = new DateTime(2023, 8, 3) },
                new Product { Id = 50, Name = "BrightVeil Moisturizer", Description = "Lightweight daily cream with niacinamide for radiant skin.", Category = "Skincare", Price = 34.99m, Quantity = 140, MediaUrl = "https://example.com/media/pureglow_moisturizer.jpg", DiscountPercentage = 20, BrandId = 9, CreatedAt = new DateTime(2021, 10, 29) },
                new Product { Id = 51, Name = "PureCure Mask", Description = "Detoxifying clay mask that purifies pores naturally.", Category = "Skincare", Price = 29.99m, Quantity = 150, MediaUrl = "https://example.com/media/pureglow_mask.jpg", DiscountPercentage = 30, BrandId = 9, CreatedAt = new DateTime(2020, 7, 21) },
                new Product { Id = 52, Name = "GlowHydra Serum", Description = "Deep hydration serum enriched with hyaluronic acid.", Category = "Skincare", Price = 44.99m, Quantity = 130, MediaUrl = "https://example.com/media/pureglow_serum.jpg", DiscountPercentage = 40, BrandId = 9, CreatedAt = new DateTime(2024, 3, 11) },
                new Product { Id = 53, Name = "VitaLush Night Cream", Description = "Nourishing night cream with plant-based peptides.", Category = "Skincare", Price = 39.99m, Quantity = 120, MediaUrl = "https://example.com/media/pureglow_nightcream.jpg", BrandId = 9, CreatedAt = new DateTime(2022, 12, 16) },
                new Product { Id = 54, Name = "FreshTone Toner", Description = "Balancing toner that smooths skin and reduces shine.", Category = "Skincare", Price = 22.99m, Quantity = 160, MediaUrl = "https://example.com/media/pureglow_toner.jpg", BrandId = 9, CreatedAt = new DateTime(2025, 5, 8) },
                    
                // -------------------- Brand 10: Trendora – Curated fashion for trendsetters --------------------
                new Product { Id = 55, Name = "VelvetEdge Dress", Description = "Chic velvet dress perfect for evening occasions.", Category = "Clothing", Price = 89.99m, Quantity = 90, MediaUrl = "https://example.com/media/trendora_dress.jpg", DiscountPercentage = 10, BrandId = 10, CreatedAt = new DateTime(2020, 10, 15) },
                new Product { Id = 56, Name = "UrbanGleam Jacket", Description = "Metallic cropped jacket for a bold statement look.", Category = "Outerwear", Price = 119.99m, Quantity = 80, MediaUrl = "https://example.com/media/trendora_jacket.jpg", DiscountPercentage = 20, BrandId = 10, CreatedAt = new DateTime(2022, 2, 7) },
                new Product { Id = 57, Name = "ChromaSneak Shoes", Description = "Color-shifting sneakers that stand out everywhere.", Category = "Footwear", Price = 99.99m, Quantity = 120, MediaUrl = "https://example.com/media/trendora_sneakers.jpg", DiscountPercentage = 30, BrandId = 10, CreatedAt = new DateTime(2023, 12, 23) },
                new Product { Id = 58, Name = "LuxeLine Handbag", Description = "Elegant faux-leather handbag with gold accents.", Category = "Accessories", Price = 149.99m, Quantity = 70, MediaUrl = "https://example.com/media/trendora_bag.jpg", DiscountPercentage = 40, BrandId = 10, CreatedAt = new DateTime(2025, 1, 2) },
                new Product { Id = 59, Name = "PulseFit Crop Top", Description = "Trendy cropped top for modern streetwear style.", Category = "Clothing", Price = 39.99m, Quantity = 150, MediaUrl = "https://example.com/media/trendora_croptop.jpg", BrandId = 10, CreatedAt = new DateTime(2024, 6, 28) },
                new Product { Id = 60, Name = "NeoAura Sunglasses", Description = "Retro-futuristic shades with UV400 protection.", Category = "Accessories", Price = 59.99m, Quantity = 200, MediaUrl = "https://example.com/media/trendora_sunglasses.jpg", BrandId = 10, CreatedAt = new DateTime(2021, 4, 6) }

                ]);
        }
    }
}
