using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ReelsCommerceSystem.Domain.Entities.ProductEntites;


namespace ReelsCommerceSystem.Infrastructure.Persistence.DataSeeding;

public class ProductSeeding : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
        var ProductsBaseUrl = @"Products/";
        builder.HasData(new Product[]
        {
            // -------------------- Brand 1: NovaWear – Sustainable fashion --------------------
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 1, Name = "EcoFlex T-Shirt", Description = "Breathable organic cotton tee for everyday comfort.", CategoryId = 1, Price = 180.00m, Quantity = 120, MediaUrl=ProductsBaseUrl+"Brand1/EcoFlexT-Shirt.png", IsCustomizable = false, DiscountPercentage = 10, BrandId = 1, CreatedAt = new DateTime(2022, 4, 12, 0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 2, Name = "ReVibe Denim Jacket", Description = "Stylish recycled denim jacket for a sustainable look.", CategoryId = 1, Price = 420.00m, Quantity = 80, MediaUrl = ProductsBaseUrl+"Brand1/ReVibe Denim Jacket.jfif", IsCustomizable = true, DiscountPercentage = 20, BrandId = 1, CreatedAt = new DateTime(2024, 2, 5, 0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 3, Name = "EcoStride Sneakers", Description = "Lightweight sneakers made from recycled fibers.", CategoryId = 2, Price = 360.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand1/EcoStride Sneakers.jfif", IsCustomizable = false, DiscountPercentage = 30, BrandId = 1, CreatedAt = new DateTime(2021, 8, 19,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 4, Name = "Bamboo Breeze Hoodie", Description = "Soft hoodie crafted from sustainable bamboo fabric.", CategoryId = 1, Price = 280.00m, Quantity = 100, MediaUrl = ProductsBaseUrl+"Brand1/Bamboo Breeze Hoodie.png", IsCustomizable = true, DiscountPercentage = 40, BrandId = 1, CreatedAt = new DateTime(2023, 5, 7,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 5, Name = "ReLeaf Tote Bag", Description = "Eco-friendly tote bag with minimalist design.", CategoryId = 3, Price = 150.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand1/ReLeaf Tote Bag.jfif", IsCustomizable = false, BrandId = 1, CreatedAt = new DateTime(2020, 9, 28,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 6, Name = "NatureFlow Pants", Description = "Comfortable pants made from recycled polyester.", CategoryId = 1, Price = 310.00m, Quantity = 90, MediaUrl = ProductsBaseUrl+"Brand1/NatureFlow Pants.webp", IsCustomizable = false, BrandId = 1, CreatedAt = new DateTime(2025, 3, 14,0,0,0, DateTimeKind.Utc) },
            
            // -------------------- Brand 2: TechEase – Smart accessories --------------------
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 7, Name = "SyncCharge Cable", Description = "Fast-charging braided USB-C cable with smart chip.", CategoryId = 4, Price = 180.00m, Quantity = 300, MediaUrl = ProductsBaseUrl+"Brand2/SyncCharge Cable.jfif", DiscountPercentage = 10, BrandId = 2, CreatedAt = new DateTime(2024, 8, 22,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 8, Name = "SmartDock Pro", Description = "Multi-device charging dock with wireless pad.", CategoryId = 4, Price = 420.00m, Quantity = 120, MediaUrl = ProductsBaseUrl+"Brand2/SmartDock Pro.jfif", DiscountPercentage = 20, BrandId = 2, CreatedAt = new DateTime(2021, 12, 3,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 9, Name = "AirPulse Earbuds", Description = "Noise-cancelling Bluetooth earbuds with 24h battery.", CategoryId = 5, Price = 540.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand2/AirPulse Earbuds.jfif", DiscountPercentage = 30, BrandId = 2, CreatedAt = new DateTime(2022, 6, 9,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 10, Name = "MagGrip Phone Mount", Description = "Smart magnetic car mount with auto-lock system.", CategoryId = 3, Price = 190.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand2/MagGrip Phone Mount.jfif", DiscountPercentage = 40, BrandId = 2, CreatedAt = new DateTime(2023, 11, 18,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 11, Name = "PulseTrack Watch", Description = "Fitness smartwatch with heart-rate and sleep tracking.", CategoryId = 6, Price = 690.00m, Quantity = 80, MediaUrl = ProductsBaseUrl+"Brand2/PulseTrack Watch.jfif", BrandId = 2, CreatedAt = new DateTime(2020, 5, 13,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 12, Name = "GlideCase", Description = "MagSafe-compatible slim phone case.", CategoryId = 3, Price = 160.00m, Quantity = 180, MediaUrl = ProductsBaseUrl+"Brand2/GlideCase.jfif", BrandId = 2, CreatedAt = new DateTime(2025, 1, 4,0,0,0, DateTimeKind.Utc) },
            
            // -------------------- Brand 3: Glowify – Natural skincare --------------------
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 13, Name = "HydraBloom Serum", Description = "Vitamin C serum that brightens and smooths skin.", CategoryId = 7, Price = 250.00m, Quantity = 120, MediaUrl = ProductsBaseUrl+"Brand3/HydraBloom Serum.jpg", DiscountPercentage = 10, BrandId = 3, CreatedAt = new DateTime(2023, 2, 25,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 14, Name = "PureDew Cleanser", Description = "Gentle cleanser with aloe and green tea.", CategoryId = 7, Price = 180.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand3/PureDew Cleanser.png", DiscountPercentage = 20, BrandId = 3, CreatedAt = new DateTime(2021, 7, 14,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 15, Name = "LumiMist Toner", Description = "Hydrating toner that refines pores naturally.", CategoryId = 7, Price = 210.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand3/LumiMist Toner.webp", DiscountPercentage = 30, BrandId = 3, CreatedAt = new DateTime(2022, 10, 9,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 16, Name = "Radiant Night Cream", Description = "Rich moisturizer for overnight skin repair.", CategoryId = 7, Price = 330.00m, Quantity = 100, MediaUrl = ProductsBaseUrl+"Brand3/Radiant Night Cream.webp", DiscountPercentage = 40, BrandId = 3, CreatedAt = new DateTime(2024, 3, 27,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 17, Name = "GlowShield Sunscreen", Description = "SPF 50 mineral sunscreen with lightweight feel.", CategoryId = 7, Price = 290.00m, Quantity = 180, MediaUrl = ProductsBaseUrl+"Brand3/GlowShield Sunscreen.jpg", BrandId = 3, CreatedAt = new DateTime(2020, 9, 10,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 18, Name = "SilkTouch Moisturizer", Description = "All-day hydration for sensitive skin.", CategoryId = 7, Price = 270.00m, Quantity = 160, MediaUrl = ProductsBaseUrl+"Brand3/SilkTouch Moisturizer.png", BrandId = 3, CreatedAt = new DateTime(2025, 4, 2,0,0,0, DateTimeKind.Utc) },
            
            // -------------------- Brand 4: UrbanFuel – Premium streetwear --------------------
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),Id = 19, Name = "StreetCore Hoodie", Description = "Oversized hoodie with minimalist street-style logo.", CategoryId = 1, Price = 320.00m, Quantity = 120, MediaUrl = ProductsBaseUrl+"Brand4/StreetCore Hoodie.png", DiscountPercentage = 10, BrandId = 4, CreatedAt = new DateTime(2022, 12, 16,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),Id = 20, Name = "UrbanFlex Joggers", Description = "Slim-fit joggers for comfort and performance.", CategoryId = 1, Price = 270.00m, Quantity = 100, MediaUrl = ProductsBaseUrl+"Brand4/UrbanFlex Joggers.png", DiscountPercentage = 20, BrandId = 4, CreatedAt = new DateTime(2024, 8, 7,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),Id = 21, Name = "FuelRunner Sneakers", Description = "Modern street sneakers with breathable mesh upper.", CategoryId = 2, Price = 540.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand4/FuelRunner Sneakers.png", DiscountPercentage = 30, BrandId = 4, CreatedAt = new DateTime(2021, 3, 2,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),Id = 22, Name = "CityWave Jacket", Description = "Lightweight windbreaker with waterproof coating.", CategoryId = 8, Price = 620.00m, Quantity = 80, MediaUrl = ProductsBaseUrl+"Brand4/CityWave Jacket.png", DiscountPercentage = 40, BrandId = 4, CreatedAt = new DateTime(2023, 10, 20,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),Id = 23, Name = "SnapEdge Cap", Description = "Classic snapback cap with embroidered logo.", CategoryId = 3, Price = 180.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand4/SnapEdge Cap.webp", BrandId = 4, CreatedAt = new DateTime(2020, 5, 29,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),Id = 24, Name = "MetroLayer Tee", Description = "Soft cotton tee with subtle reflective branding.", CategoryId = 1, Price = 190.00m, Quantity = 140, MediaUrl = ProductsBaseUrl+"Brand4/MetroLayer Tee.jpg", BrandId = 4, CreatedAt = new DateTime(2025, 2, 11,0,0,0, DateTimeKind.Utc) },
            
            // -------------------- Brand 5: Zenora – Wellness lifestyle --------------------
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 25, Name = "ZenMat Pro", Description = "Premium non-slip yoga mat made with eco rubber.", CategoryId = 9, Price = 350.00m, Quantity = 110, MediaUrl = ProductsBaseUrl+"Brand5/ZenMat.webp", DiscountPercentage = 10, BrandId = 5, CreatedAt = new DateTime(2022, 6, 19,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 26, Name = "AromaBliss Diffuser", Description = "Ultrasonic diffuser with ambient lighting.", CategoryId = 10, Price = 290.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand5/AromaBliss Diffuser.webp", DiscountPercentage = 20, BrandId = 5, CreatedAt = new DateTime(2020, 11, 12,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 27, Name = "CalmWave Candle", Description = "Soy candle infused with lavender and chamomile.", CategoryId = 11, Price = 170.00m, Quantity = 180, MediaUrl = ProductsBaseUrl+"Brand5/CalmWave Candle.webp", DiscountPercentage = 30, BrandId = 5, CreatedAt = new DateTime(2023, 9, 15,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 28, Name = "Balance Bottle", Description = "Glass water bottle with bamboo lid and sleeve.", CategoryId = 10, Price = 210.00m, Quantity = 160, MediaUrl = ProductsBaseUrl+"Brand5/Balance Bottle.webp", DiscountPercentage = 40, BrandId = 5, CreatedAt = new DateTime(2024, 1, 6,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 29, Name = "Focus Journal", Description = "Guided journal for mindfulness and productivity.", CategoryId = 12, Price = 150.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand5/Focus Journal.webp", BrandId = 5, CreatedAt = new DateTime(2025, 3, 25,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 30, Name = "Serenity Pillow Spray", Description = "Natural lavender mist for better sleep.", CategoryId = 10, Price = 180.00m, Quantity = 180, MediaUrl = ProductsBaseUrl+"Brand5/Serenity Pillow Spray.jpg", BrandId = 5, CreatedAt = new DateTime(2021, 4, 17,0,0,0, DateTimeKind.Utc) },
            
            // -------------------- Brand 6: AeroFit – Smart fitness gear --------------------
            new Product {UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 31, Name = "AeroTrack Smart Band", Description = "Fitness tracker with pulse and oxygen monitoring.", CategoryId = 6, Price = 540.00m, Quantity = 130, MediaUrl = ProductsBaseUrl+"Brand6/AeroTrack Smart Band.png", DiscountPercentage = 10, BrandId = 6, CreatedAt = new DateTime(2020, 10, 3,0,0,0, DateTimeKind.Utc) },
            new Product {UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 32, Name = "FlexCore Dumbbells", Description = "Adjustable dumbbells for home strength training.", CategoryId = 13, Price = 720.00m, Quantity = 90, MediaUrl = ProductsBaseUrl+"Brand6/bowflex-dumbbells.jpg", DiscountPercentage = 20, BrandId = 6, CreatedAt = new DateTime(2025, 1, 20,0,0,0, DateTimeKind.Utc) },
            new Product {UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 33, Name = "PulsePro Chest Strap", Description = "Heart-rate strap compatible with popular apps.", CategoryId = 3, Price = 210.00m, Quantity = 100, MediaUrl = ProductsBaseUrl+"Brand6/PulsePro Chest Strap.webp", DiscountPercentage = 30, BrandId = 6, CreatedAt = new DateTime(2023, 2, 8,0,0,0, DateTimeKind.Utc) },
            new Product {UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 34, Name = "AeroMat Trainer", Description = "High-density mat ideal for HIIT and yoga.", CategoryId = 9, Price = 250.00m, Quantity = 140, MediaUrl = ProductsBaseUrl+"Brand6/AeroMat Trainer.webp", DiscountPercentage = 40, BrandId = 6, CreatedAt = new DateTime(2022, 11, 22,0,0,0, DateTimeKind.Utc) },
            new Product {UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 35, Name = "HydraFuel Bottle", Description = "Smart bottle that tracks hydration levels.", CategoryId = 3, Price = 170.00m, Quantity = 160, MediaUrl = ProductsBaseUrl+"Brand6/HydraFuel Bottle.jfif", BrandId = 6, CreatedAt = new DateTime(2024, 6, 11,0,0,0, DateTimeKind.Utc) },
            new Product {UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 36, Name = "TrainLite Shorts", Description = "Lightweight shorts with moisture-wicking tech.", CategoryId = 14, Price = 260.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand6/TrainLite Shorts.jpg", BrandId = 6, CreatedAt = new DateTime(2021, 9, 1,0,0,0, DateTimeKind.Utc) },
            
            // -------------------- Brand 7: EcoNest – Eco-friendly home solutions --------------------
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 37, Name = "EcoGlow Lamp", Description = "Bamboo desk lamp with rechargeable LED bulb.", CategoryId = 15, Price = 250.00m, Quantity = 110, MediaUrl = ProductsBaseUrl+"Brand7/EcoGlow Lamp.webp", DiscountPercentage = 10, BrandId = 7, CreatedAt = new DateTime(2022, 5, 12,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 38, Name = "GreenWave Blanket", Description = "Soft throw blanket made from recycled cotton.", CategoryId = 11, Price = 320.00m, Quantity = 100, MediaUrl = ProductsBaseUrl+"Brand7/GreenWave Blanket.jfif", DiscountPercentage = 20, BrandId = 7, CreatedAt = new DateTime(2023, 8, 9,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 39, Name = "PlantPure Planter Set", Description = "Biodegradable planters perfect for indoor herbs.", CategoryId = 16, Price = 180.00m, Quantity = 180, MediaUrl = ProductsBaseUrl+"Brand7/PlantPure Planter Set.jpg", DiscountPercentage = 30, BrandId = 7, CreatedAt = new DateTime(2021, 10, 14,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 40, Name = "EcoFresh Diffuser", Description = "Natural reed diffuser with citrus essential oils.", CategoryId = 17, Price = 210.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand7/EcoFresh Diffuser.webp", DiscountPercentage = 40, BrandId = 7, CreatedAt = new DateTime(2024, 2, 27,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 41, Name = "PureBreeze Air Filter", Description = "Reusable air filter system for cleaner home air.", CategoryId = 18, Price = 640.00m, Quantity = 90, MediaUrl = ProductsBaseUrl+"Brand7/PureBreeze Air Filter.webp", BrandId = 7, CreatedAt = new DateTime(2020, 6, 22,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 42, Name = "Harmony Coasters", Description = "Cork coasters made from renewable materials.", CategoryId = 16, Price = 160.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand7/Harmony Coasters.jfif", BrandId = 7, CreatedAt = new DateTime(2025, 1, 19,0,0,0, DateTimeKind.Utc) },
            
            // -------------------- Brand 8: ByteWave – Tech-driven accessories --------------------
            new Product {UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),Id = 43, Name = "VoltSync Charger", Description = "High-speed GaN charger with dual USB-C output.", CategoryId = 4, Price = 280.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand8/VoltSync Charger.webp", DiscountPercentage = 10, BrandId = 8, CreatedAt = new DateTime(2021, 9, 23,0,0,0, DateTimeKind.Utc) },
            new Product {UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),Id = 44, Name = "StreamPad Mouse", Description = "Ergonomic wireless mouse with silent clicks.", CategoryId = 3, Price = 240.00m, Quantity = 180, MediaUrl = ProductsBaseUrl+"Brand8/StreamPad Mouse.jpg", DiscountPercentage = 20, BrandId = 8, CreatedAt = new DateTime(2023, 11, 5,0,0,0, DateTimeKind.Utc) },
            new Product {UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),Id = 45, Name = "DataShell SSD Case", Description = "Shockproof case for portable SSDs.", CategoryId = 18, Price = 190.00m, Quantity = 220, MediaUrl = ProductsBaseUrl+"Brand8/DataShell SSD Case.jpg", DiscountPercentage = 30, BrandId = 8, CreatedAt = new DateTime(2022, 4, 17,0,0,0, DateTimeKind.Utc) },
            new Product {UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),Id = 46, Name = "WavePods Mini", Description = "Compact true wireless earbuds with clear audio.", CategoryId = 5, Price = 420.00m, Quantity = 140, MediaUrl = ProductsBaseUrl+"Brand8/WavePods Mini.jpg", DiscountPercentage = 40, BrandId = 8, CreatedAt = new DateTime(2024, 9, 30,0,0,0, DateTimeKind.Utc) },
            new Product {UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),Id = 47, Name = "NeonLink Cable Set", Description = "AvailableColors-coded USB-C and Lightning cable pack.", CategoryId = 3, Price = 160.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand8/NeonLink Cable Set.webp", BrandId = 8, CreatedAt = new DateTime(2020, 3, 14,0,0,0, DateTimeKind.Utc) },
            new Product {UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),Id = 48, Name = "GlideStand Laptop Dock", Description = "Foldable aluminum laptop stand with cooling vents.", CategoryId = 19, Price = 360.00m, Quantity = 130, MediaUrl = ProductsBaseUrl+"Brand8/GlideStand Laptop Dock.jpg", BrandId = 8, CreatedAt = new DateTime(2025, 7, 26,0,0,0, DateTimeKind.Utc) },
            
            // -------------------- Brand 9: PureGlow – Clean & ethical skincare --------------------
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 49, Name = "AquaRenew Cleanser", Description = "Refreshing foaming cleanser for daily use.", CategoryId = 7, Price = 180.00m, Quantity = 160, MediaUrl = ProductsBaseUrl+"Brand9/AquaRenew Cleanser.png", DiscountPercentage = 10, BrandId = 9, CreatedAt = new DateTime(2023, 8, 3,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 50, Name = "BrightVeil Moisturizer", Description = "Lightweight daily cream with niacinamide for radiant skin.", CategoryId = 7, Price = 220.00m, Quantity = 140, MediaUrl = ProductsBaseUrl+"Brand9/BrightVeil Moisturizer.png", DiscountPercentage = 20, BrandId = 9, CreatedAt = new DateTime(2021, 10, 29,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 51, Name = "PureCure Mask", Description = "Detoxifying clay mask that purifies pores naturally.", CategoryId = 7, Price = 240.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand9/PureCure Mask.jpg", DiscountPercentage = 30, BrandId = 9, CreatedAt = new DateTime(2020, 7, 21,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 52, Name = "GlowHydra Serum", Description = "Deep hydration serum enriched with hyaluronic acid.", CategoryId = 7, Price = 390.00m, Quantity = 130, MediaUrl = ProductsBaseUrl+"Brand9/GlowHydra Serum.webp", DiscountPercentage = 40, BrandId = 9, CreatedAt = new DateTime(2024, 3, 11,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 53, Name = "VitaLush Night Cream", Description = "Nourishing night cream with plant-based peptides.", CategoryId = 7, Price = 260.00m, Quantity = 120, MediaUrl = ProductsBaseUrl+"Brand9/VitaLush Night Cream.webp", BrandId = 9, CreatedAt = new DateTime(2022, 12, 16,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 54, Name = "FreshTone Toner", Description = "Balancing toner that smooths skin and reduces shine.", CategoryId = 7, Price = 210.00m, Quantity = 160, MediaUrl = ProductsBaseUrl+"Brand9/FreshTone Toner.webp", BrandId = 9, CreatedAt = new DateTime(2025, 5, 8,0,0,0, DateTimeKind.Utc) },
            
            // -------------------- Brand 10: Trendora – Curated fashion for trendsetters --------------------
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 55, Name = "VelvetEdge Dress", Description = "Chic velvet dress perfect for evening occasions.", CategoryId = 1, Price = 780.00m, Quantity = 90, MediaUrl = ProductsBaseUrl+"Brand10/VelvetEdge Dress.webp", DiscountPercentage = 10, BrandId = 10, CreatedAt = new DateTime(2020, 10, 15,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 56, Name = "UrbanGleam Jacket", Description = "Metallic cropped jacket for a bold statement look.", CategoryId = 8, Price = 650.00m, Quantity = 80, MediaUrl = ProductsBaseUrl+"Brand10/UrbanGleam Jacket.jfif", DiscountPercentage = 20, BrandId = 10, CreatedAt = new DateTime(2022, 2, 7,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 57, Name = "ChromaSneak Shoes", Description = "AvailableColors-shifting sneakers that stand out everywhere.", CategoryId = 2, Price = 540.00m, Quantity = 120, MediaUrl = ProductsBaseUrl+"Brand10/ChromaSneak Shoes.webp", DiscountPercentage = 30, BrandId = 10, CreatedAt = new DateTime(2023, 12, 23,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 58, Name = "LuxeLine Handbag", Description = "Elegant faux-leather handbag with gold accents.", CategoryId = 3, Price = 720.00m, Quantity = 70, MediaUrl = ProductsBaseUrl+"Brand10/LuxeLine Handbag.jfif", DiscountPercentage = 40, BrandId = 10, CreatedAt = new DateTime(2025, 1, 2,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 59, Name = "PulseFit Crop Top", Description = "Trendy cropped top for modern streetwear style.", CategoryId = 1, Price = 190.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand10/PulseFit Crop Top.webp", BrandId = 10, CreatedAt = new DateTime(2024, 6, 28,0,0,0, DateTimeKind.Utc) },
            new Product { UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc), Id = 60, Name = "NeoAura Sunglasses", Description = "Retro-futuristic shades with UV400 protection.", CategoryId = 3, Price = 350.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand10/NeoAura Sunglasses.jfif", BrandId = 10, CreatedAt = new DateTime(2021, 4, 6,0,0,0, DateTimeKind.Utc) }

        });
    }
}
