using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ReelsCommerceSystem.Domain.Entities.ProductEntites;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReelsCommerceSystem.Infrastructure.Persistence.DataSeeding
{
    public class ProductSeeding : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> builder)
        {
            var ProductsBaseUrl = @"D:\Nada\GradProject\ReelsCommerceSystem\ReelsCommerceSystem.Api\wwwroot\Products\";
            builder.HasData([
                //D:\Nada\GradProject\ReelsCommerceSystem\ReelsCommerceSystem.Api\wwwroot\Products\Brand1\Bamboo Breeze Hoodie.png
                // -------------------- Brand 1: NovaWear – Sustainable fashion --------------------
                new Product { Id = 1, Name = "EcoFlex T-Shirt", Description = "Breathable organic cotton tee for everyday comfort.", Category = "Clothing", Price = 180.00m, Quantity = 120, MediaUrl=ProductsBaseUrl+"Brand1\\EcoFlexT-Shirt.png", IsCustomizable = false, DiscountPercentage = 10, BrandId = 1, CreatedAt = new DateTime(2022, 4, 12) },
                new Product { Id = 2, Name = "ReVibe Denim Jacket", Description = "Stylish recycled denim jacket for a sustainable look.", Category = "Clothing", Price = 420.00m, Quantity = 80, MediaUrl = ProductsBaseUrl+"Brand1\\ReVibe Denim Jacket.jfif", IsCustomizable = true, DiscountPercentage = 20, BrandId = 1, CreatedAt = new DateTime(2024, 2, 5) },
                new Product { Id = 3, Name = "EcoStride Sneakers", Description = "Lightweight sneakers made from recycled fibers.", Category = "Footwear", Price = 360.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand1\\EcoStride Sneakers.jfif", IsCustomizable = false, DiscountPercentage = 30, BrandId = 1, CreatedAt = new DateTime(2021, 8, 19) },
                new Product { Id = 4, Name = "Bamboo Breeze Hoodie", Description = "Soft hoodie crafted from sustainable bamboo fabric.", Category = "Clothing", Price = 280.00m, Quantity = 100, MediaUrl = ProductsBaseUrl+"Brand1\\Bamboo Breeze Hoodie.png", IsCustomizable = true, DiscountPercentage = 40, BrandId = 1, CreatedAt = new DateTime(2023, 5, 7) },
                new Product { Id = 5, Name = "ReLeaf Tote Bag", Description = "Eco-friendly tote bag with minimalist design.", Category = "Accessories", Price = 150.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand1\\ReLeaf Tote Bag.jfif", IsCustomizable = false, BrandId = 1, CreatedAt = new DateTime(2020, 9, 28) },
                new Product { Id = 6, Name = "NatureFlow Pants", Description = "Comfortable pants made from recycled polyester.", Category = "Clothing", Price = 310.00m, Quantity = 90, MediaUrl = ProductsBaseUrl+"Brand1\\NatureFlow Pants.webp", IsCustomizable = false, BrandId = 1, CreatedAt = new DateTime(2025, 3, 14) },
                
                // -------------------- Brand 2: TechEase – Smart accessories --------------------
                new Product { Id = 7, Name = "SyncCharge Cable", Description = "Fast-charging braided USB-C cable with smart chip.", Category = "Electronics", Price = 180.00m, Quantity = 300, MediaUrl = ProductsBaseUrl+"Brand2\\SyncCharge Cable.jfif", DiscountPercentage = 10, BrandId = 2, CreatedAt = new DateTime(2024, 8, 22) },
                new Product { Id = 8, Name = "SmartDock Pro", Description = "Multi-device charging dock with wireless pad.", Category = "Electronics", Price = 420.00m, Quantity = 120, MediaUrl = ProductsBaseUrl+"Brand2\\SmartDock Pro.jfif", DiscountPercentage = 20, BrandId = 2, CreatedAt = new DateTime(2021, 12, 3) },
                new Product { Id = 9, Name = "AirPulse Earbuds", Description = "Noise-cancelling Bluetooth earbuds with 24h battery.", Category = "Audio", Price = 540.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand2\\AirPulse Earbuds.jfif", DiscountPercentage = 30, BrandId = 2, CreatedAt = new DateTime(2022, 6, 9) },
                new Product { Id = 10, Name = "MagGrip Phone Mount", Description = "Smart magnetic car mount with auto-lock system.", Category = "Accessories", Price = 190.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand2\\MagGrip Phone Mount.jfif", DiscountPercentage = 40, BrandId = 2, CreatedAt = new DateTime(2023, 11, 18) },
                new Product { Id = 11, Name = "PulseTrack Watch", Description = "Fitness smartwatch with heart-rate and sleep tracking.", Category = "Wearables", Price = 690.00m, Quantity = 80, MediaUrl = ProductsBaseUrl+"Brand2\\PulseTrack Watch.jfif", BrandId = 2, CreatedAt = new DateTime(2020, 5, 13) },
                new Product { Id = 12, Name = "GlideCase", Description = "MagSafe-compatible slim phone case.", Category = "Accessories", Price = 160.00m, Quantity = 180, MediaUrl = ProductsBaseUrl+"Brand2\\GlideCase.jfif", BrandId = 2, CreatedAt = new DateTime(2025, 1, 4) },
                
                // -------------------- Brand 3: Glowify – Natural skincare --------------------
                new Product { Id = 13, Name = "HydraBloom Serum", Description = "Vitamin C serum that brightens and smooths skin.", Category = "Skincare", Price = 250.00m, Quantity = 120, MediaUrl = ProductsBaseUrl+"Brand3\\HydraBloom Serum.jpg", DiscountPercentage = 10, BrandId = 3, CreatedAt = new DateTime(2023, 2, 25) },
                new Product { Id = 14, Name = "PureDew Cleanser", Description = "Gentle cleanser with aloe and green tea.", Category = "Skincare", Price = 180.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand3\\PureDew Cleanser.png", DiscountPercentage = 20, BrandId = 3, CreatedAt = new DateTime(2021, 7, 14) },
                new Product { Id = 15, Name = "LumiMist Toner", Description = "Hydrating toner that refines pores naturally.", Category = "Skincare", Price = 210.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand3\\LumiMist Toner.webp", DiscountPercentage = 30, BrandId = 3, CreatedAt = new DateTime(2022, 10, 9) },
                new Product { Id = 16, Name = "Radiant Night Cream", Description = "Rich moisturizer for overnight skin repair.", Category = "Skincare", Price = 330.00m, Quantity = 100, MediaUrl = ProductsBaseUrl+"Brand3\\Radiant Night Cream.webp", DiscountPercentage = 40, BrandId = 3, CreatedAt = new DateTime(2024, 3, 27) },
                new Product { Id = 17, Name = "GlowShield Sunscreen", Description = "SPF 50 mineral sunscreen with lightweight feel.", Category = "Skincare", Price = 290.00m, Quantity = 180, MediaUrl = ProductsBaseUrl+"Brand3\\GlowShield Sunscreen.jpg", BrandId = 3, CreatedAt = new DateTime(2020, 9, 10) },
                new Product { Id = 18, Name = "SilkTouch Moisturizer", Description = "All-day hydration for sensitive skin.", Category = "Skincare", Price = 270.00m, Quantity = 160, MediaUrl = ProductsBaseUrl+"Brand3\\SilkTouch Moisturizer.png", BrandId = 3, CreatedAt = new DateTime(2025, 4, 2) },
                
                // -------------------- Brand 4: UrbanFuel – Premium streetwear --------------------
                new Product { Id = 19, Name = "StreetCore Hoodie", Description = "Oversized hoodie with minimalist street-style logo.", Category = "Clothing", Price = 320.00m, Quantity = 120, MediaUrl = ProductsBaseUrl+"Brand4\\StreetCore Hoodie.png", DiscountPercentage = 10, BrandId = 4, CreatedAt = new DateTime(2022, 12, 16) },
                new Product { Id = 20, Name = "UrbanFlex Joggers", Description = "Slim-fit joggers for comfort and performance.", Category = "Clothing", Price = 270.00m, Quantity = 100, MediaUrl = ProductsBaseUrl+"Brand4\\UrbanFlex Joggers.png", DiscountPercentage = 20, BrandId = 4, CreatedAt = new DateTime(2024, 8, 7) },
                new Product { Id = 21, Name = "FuelRunner Sneakers", Description = "Modern street sneakers with breathable mesh upper.", Category = "Footwear", Price = 540.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand4\\FuelRunner Sneakers.png", DiscountPercentage = 30, BrandId = 4, CreatedAt = new DateTime(2021, 3, 2) },
                new Product { Id = 22, Name = "CityWave Jacket", Description = "Lightweight windbreaker with waterproof coating.", Category = "Outerwear", Price = 620.00m, Quantity = 80, MediaUrl = ProductsBaseUrl+"Brand4\\CityWave Jacket.png", DiscountPercentage = 40, BrandId = 4, CreatedAt = new DateTime(2023, 10, 20) },
                new Product { Id = 23, Name = "SnapEdge Cap", Description = "Classic snapback cap with embroidered logo.", Category = "Accessories", Price = 180.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand4\\SnapEdge Cap.webp", BrandId = 4, CreatedAt = new DateTime(2020, 5, 29) },
                new Product { Id = 24, Name = "MetroLayer Tee", Description = "Soft cotton tee with subtle reflective branding.", Category = "Clothing", Price = 190.00m, Quantity = 140, MediaUrl = ProductsBaseUrl+"Brand4\\MetroLayer Tee.jpg", BrandId = 4, CreatedAt = new DateTime(2025, 2, 11) },
                
                // -------------------- Brand 5: Zenora – Wellness lifestyle --------------------
                new Product { Id = 25, Name = "ZenMat Pro", Description = "Premium non-slip yoga mat made with eco rubber.", Category = "Fitness", Price = 350.00m, Quantity = 110, MediaUrl = ProductsBaseUrl+"Brand5\\ZenMat.webp", DiscountPercentage = 10, BrandId = 5, CreatedAt = new DateTime(2022, 6, 19) },
                new Product { Id = 26, Name = "AromaBliss Diffuser", Description = "Ultrasonic diffuser with ambient lighting.", Category = "Wellness", Price = 290.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand5\\AromaBliss Diffuser.webp", DiscountPercentage = 20, BrandId = 5, CreatedAt = new DateTime(2020, 11, 12) },
                new Product { Id = 27, Name = "CalmWave Candle", Description = "Soy candle infused with lavender and chamomile.", Category = "Home", Price = 170.00m, Quantity = 180, MediaUrl = ProductsBaseUrl+"Brand5\\CalmWave Candle.webp", DiscountPercentage = 30, BrandId = 5, CreatedAt = new DateTime(2023, 9, 15) },
                new Product { Id = 28, Name = "Balance Bottle", Description = "Glass water bottle with bamboo lid and sleeve.", Category = "Wellness", Price = 210.00m, Quantity = 160, MediaUrl = ProductsBaseUrl+"Brand5\\Balance Bottle.webp", DiscountPercentage = 40, BrandId = 5, CreatedAt = new DateTime(2024, 1, 6) },
                new Product { Id = 29, Name = "Focus Journal", Description = "Guided journal for mindfulness and productivity.", Category = "Stationery", Price = 150.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand5\\Focus Journal.webp", BrandId = 5, CreatedAt = new DateTime(2025, 3, 25) },
                new Product { Id = 30, Name = "Serenity Pillow Spray", Description = "Natural lavender mist for better sleep.", Category = "Wellness", Price = 180.00m, Quantity = 180, MediaUrl = ProductsBaseUrl+"Brand5\\Serenity Pillow Spray.jpg", BrandId = 5, CreatedAt = new DateTime(2021, 4, 17) },
                
                // -------------------- Brand 6: AeroFit – Smart fitness gear --------------------
                new Product { Id = 31, Name = "AeroTrack Smart Band", Description = "Fitness tracker with pulse and oxygen monitoring.", Category = "Wearables", Price = 540.00m, Quantity = 130, MediaUrl = ProductsBaseUrl+"Brand6\\AeroTrack Smart Band.png", DiscountPercentage = 10, BrandId = 6, CreatedAt = new DateTime(2020, 10, 3) },
                new Product { Id = 32, Name = "FlexCore Dumbbells", Description = "Adjustable dumbbells for home strength training.", Category = "Equipment", Price = 720.00m, Quantity = 90, MediaUrl = ProductsBaseUrl+"Brand6\\bowflex-dumbbells.jpg", DiscountPercentage = 20, BrandId = 6, CreatedAt = new DateTime(2025, 1, 20) },
                new Product { Id = 33, Name = "PulsePro Chest Strap", Description = "Heart-rate strap compatible with popular apps.", Category = "Accessories", Price = 210.00m, Quantity = 100, MediaUrl = ProductsBaseUrl+"Brand6\\PulsePro Chest Strap.webp", DiscountPercentage = 30, BrandId = 6, CreatedAt = new DateTime(2023, 2, 8) },
                new Product { Id = 34, Name = "AeroMat Trainer", Description = "High-density mat ideal for HIIT and yoga.", Category = "Fitness", Price = 250.00m, Quantity = 140, MediaUrl = ProductsBaseUrl+"Brand6\\AeroMat Trainer.webp", DiscountPercentage = 40, BrandId = 6, CreatedAt = new DateTime(2022, 11, 22) },
                new Product { Id = 35, Name = "HydraFuel Bottle", Description = "Smart bottle that tracks hydration levels.", Category = "Accessories", Price = 170.00m, Quantity = 160, MediaUrl = ProductsBaseUrl+"Brand6\\HydraFuel Bottle.jfif", BrandId = 6, CreatedAt = new DateTime(2024, 6, 11) },
                new Product { Id = 36, Name = "TrainLite Shorts", Description = "Lightweight shorts with moisture-wicking tech.", Category = "Apparel", Price = 260.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand6\\TrainLite Shorts.jpg", BrandId = 6, CreatedAt = new DateTime(2021, 9, 1) },
                
                // -------------------- Brand 7: EcoNest – Eco-friendly home solutions --------------------
                new Product { Id = 37, Name = "EcoGlow Lamp", Description = "Bamboo desk lamp with rechargeable LED bulb.", Category = "Home Decor", Price = 250.00m, Quantity = 110, MediaUrl = ProductsBaseUrl+"Brand7\\EcoGlow Lamp.webp", DiscountPercentage = 10, BrandId = 7, CreatedAt = new DateTime(2022, 5, 12) },
                new Product { Id = 38, Name = "GreenWave Blanket", Description = "Soft throw blanket made from recycled cotton.", Category = "Home", Price = 320.00m, Quantity = 100, MediaUrl = ProductsBaseUrl+"Brand7\\GreenWave Blanket.jfif", DiscountPercentage = 20, BrandId = 7, CreatedAt = new DateTime(2023, 8, 9) },
                new Product { Id = 39, Name = "PlantPure Planter Set", Description = "Biodegradable planters perfect for indoor herbs.", Category = "Gardening", Price = 180.00m, Quantity = 180, MediaUrl = ProductsBaseUrl+"Brand7\\PlantPure Planter Set.jpg", DiscountPercentage = 30, BrandId = 7, CreatedAt = new DateTime(2021, 10, 14) },
                new Product { Id = 40, Name = "EcoFresh Diffuser", Description = "Natural reed diffuser with citrus essential oils.", Category = "Home Fragrance", Price = 210.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand7\\EcoFresh Diffuser.webp", DiscountPercentage = 40, BrandId = 7, CreatedAt = new DateTime(2024, 2, 27) },
                new Product { Id = 41, Name = "PureBreeze Air Filter", Description = "Reusable air filter system for cleaner home air.", Category = "Appliances", Price = 640.00m, Quantity = 90, MediaUrl = ProductsBaseUrl+"Brand7\\PureBreeze Air Filter.webp", BrandId = 7, CreatedAt = new DateTime(2020, 6, 22) },
                new Product { Id = 42, Name = "Harmony Coasters", Description = "Cork coasters made from renewable materials.", Category = "Home Accessories", Price = 160.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand7\\Harmony Coasters.jfif", BrandId = 7, CreatedAt = new DateTime(2025, 1, 19) },
                
                // -------------------- Brand 8: ByteWave – Tech-driven accessories --------------------
                new Product { Id = 43, Name = "VoltSync Charger", Description = "High-speed GaN charger with dual USB-C output.", Category = "Electronics", Price = 280.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand8\\VoltSync Charger.webp", DiscountPercentage = 10, BrandId = 8, CreatedAt = new DateTime(2021, 9, 23) },
                new Product { Id = 44, Name = "StreamPad Mouse", Description = "Ergonomic wireless mouse with silent clicks.", Category = "Accessories", Price = 240.00m, Quantity = 180, MediaUrl = ProductsBaseUrl+"Brand8\\StreamPad Mouse.jpg", DiscountPercentage = 20, BrandId = 8, CreatedAt = new DateTime(2023, 11, 5) },
                new Product { Id = 45, Name = "DataShell SSD Case", Description = "Shockproof case for portable SSDs.", Category = "Storage", Price = 190.00m, Quantity = 220, MediaUrl = ProductsBaseUrl+"Brand8\\DataShell SSD Case.jpg", DiscountPercentage = 30, BrandId = 8, CreatedAt = new DateTime(2022, 4, 17) },
                new Product { Id = 46, Name = "WavePods Mini", Description = "Compact true wireless earbuds with clear audio.", Category = "Audio", Price = 420.00m, Quantity = 140, MediaUrl = ProductsBaseUrl+"Brand8\\WavePods Mini.jpg", DiscountPercentage = 40, BrandId = 8, CreatedAt = new DateTime(2024, 9, 30) },
                new Product { Id = 47, Name = "NeonLink Cable Set", Description = "Color-coded USB-C and Lightning cable pack.", Category = "Accessories", Price = 160.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand8\\NeonLink Cable Set.webp", BrandId = 8, CreatedAt = new DateTime(2020, 3, 14) },
                new Product { Id = 48, Name = "GlideStand Laptop Dock", Description = "Foldable aluminum laptop stand with cooling vents.", Category = "Office", Price = 360.00m, Quantity = 130, MediaUrl = ProductsBaseUrl+"Brand8\\GlideStand Laptop Dock.jpg", BrandId = 8, CreatedAt = new DateTime(2025, 7, 26) },
                
                // -------------------- Brand 9: PureGlow – Clean & ethical skincare --------------------
                new Product { Id = 49, Name = "AquaRenew Cleanser", Description = "Refreshing foaming cleanser for daily use.", Category = "Skincare", Price = 180.00m, Quantity = 160, MediaUrl = ProductsBaseUrl+"Brand9\\AquaRenew Cleanser.png", DiscountPercentage = 10, BrandId = 9, CreatedAt = new DateTime(2023, 8, 3) },
                new Product { Id = 50, Name = "BrightVeil Moisturizer", Description = "Lightweight daily cream with niacinamide for radiant skin.", Category = "Skincare", Price = 220.00m, Quantity = 140, MediaUrl = ProductsBaseUrl+"Brand9\\BrightVeil Moisturizer.png", DiscountPercentage = 20, BrandId = 9, CreatedAt = new DateTime(2021, 10, 29) },
                new Product { Id = 51, Name = "PureCure Mask", Description = "Detoxifying clay mask that purifies pores naturally.", Category = "Skincare", Price = 240.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand9\\PureCure Mask.jpg", DiscountPercentage = 30, BrandId = 9, CreatedAt = new DateTime(2020, 7, 21) },
                new Product { Id = 52, Name = "GlowHydra Serum", Description = "Deep hydration serum enriched with hyaluronic acid.", Category = "Skincare", Price = 390.00m, Quantity = 130, MediaUrl = ProductsBaseUrl+"Brand9\\GlowHydra Serum.webp", DiscountPercentage = 40, BrandId = 9, CreatedAt = new DateTime(2024, 3, 11) },
                new Product { Id = 53, Name = "VitaLush Night Cream", Description = "Nourishing night cream with plant-based peptides.", Category = "Skincare", Price = 260.00m, Quantity = 120, MediaUrl = ProductsBaseUrl+"Brand9\\VitaLush Night Cream.webp", BrandId = 9, CreatedAt = new DateTime(2022, 12, 16) },
                new Product { Id = 54, Name = "FreshTone Toner", Description = "Balancing toner that smooths skin and reduces shine.", Category = "Skincare", Price = 210.00m, Quantity = 160, MediaUrl = ProductsBaseUrl+"Brand9\\FreshTone Toner.webp", BrandId = 9, CreatedAt = new DateTime(2025, 5, 8) },
                
                // -------------------- Brand 10: Trendora – Curated fashion for trendsetters --------------------
                new Product { Id = 55, Name = "VelvetEdge Dress", Description = "Chic velvet dress perfect for evening occasions.", Category = "Clothing", Price = 780.00m, Quantity = 90, MediaUrl = ProductsBaseUrl+"Brand10\\VelvetEdge Dress.webp", DiscountPercentage = 10, BrandId = 10, CreatedAt = new DateTime(2020, 10, 15) },
                new Product { Id = 56, Name = "UrbanGleam Jacket", Description = "Metallic cropped jacket for a bold statement look.", Category = "Outerwear", Price = 650.00m, Quantity = 80, MediaUrl = ProductsBaseUrl+"Brand10\\UrbanGleam Jacket.jfif", DiscountPercentage = 20, BrandId = 10, CreatedAt = new DateTime(2022, 2, 7) },
                new Product { Id = 57, Name = "ChromaSneak Shoes", Description = "Color-shifting sneakers that stand out everywhere.", Category = "Footwear", Price = 540.00m, Quantity = 120, MediaUrl = ProductsBaseUrl+"Brand10\\ChromaSneak Shoes.webp", DiscountPercentage = 30, BrandId = 10, CreatedAt = new DateTime(2023, 12, 23) },
                new Product { Id = 58, Name = "LuxeLine Handbag", Description = "Elegant faux-leather handbag with gold accents.", Category = "Accessories", Price = 720.00m, Quantity = 70, MediaUrl = ProductsBaseUrl+"Brand10\\LuxeLine Handbag.jfif", DiscountPercentage = 40, BrandId = 10, CreatedAt = new DateTime(2025, 1, 2) },
                new Product { Id = 59, Name = "PulseFit Crop Top", Description = "Trendy cropped top for modern streetwear style.", Category = "Clothing", Price = 190.00m, Quantity = 150, MediaUrl = ProductsBaseUrl+"Brand10\\PulseFit Crop Top.webp", BrandId = 10, CreatedAt = new DateTime(2024, 6, 28) },
                new Product { Id = 60, Name = "NeoAura Sunglasses", Description = "Retro-futuristic shades with UV400 protection.", Category = "Accessories", Price = 350.00m, Quantity = 200, MediaUrl = ProductsBaseUrl+"Brand10\\NeoAura Sunglasses.jfif", BrandId = 10, CreatedAt = new DateTime(2021, 4, 6) }

                ]);
        }
    }
}
